# test_dbt_project:
#   target: dev
#   outputs:
#     dev:
#       type: postgres
#       host: localhost
#       user: nicholas
#       password: root
#       port: 5432
#       dbname: postgres
#       schema: public
#       threads: 1
#       connect_timeout: 30